Wolfieheart/ArmorStandEditor

src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java
Signed-off-by: Wolfstorm <xMakeItRain94@gmail.com>
=> [CORE] Add bStats Metrics

README.md, pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/CommandEx.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditor.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java, src/main/resources/config.yml, src/main/resources/plugin.yml
For all the things merged into 1.18.1-32.
Change Log:
- Fix for Scoreboards: https://github.com/Wolfst0rm/ArmorStandEditor-Issues/issues/18 - Implemented
- https://github.com/Wolfst0rm/ArmorStandEditor-Issues/issues/17 - Implemented
- https://github.com/Wolfst0rm/ArmorStandEditor-Issues/issues/16 - UpdateChecker Implemented
- Extra debug output
- Toggle for setting things invisible - 2 new config options and split of asedit.invisible permission node
- Version and Update Commands
More to come. Preliminary Changelog.
=> Version: ArmorStandEditor 1.18.1-32

README.md, pom.xml, src/main/java/META-INF/MANIFEST.MF, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/Menu.java, src/main/resources/config.yml, src/main/resources/plugin.yml
=> Version: ArmorStandEditor 1.18.1-33

.github/workflows/maven-publish.yml, pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java, src/main/resources/plugin.yml
Hotfix Update for PlayerInteractAtEntityEvent Double Firing
Signed-off-by: Wolfieheart <xMakeItRain94@gmail.com>
=> [CORE] ArmorStandEditor v1.18.1-33.1

.github/workflows/maven-publish.yml, README.md, pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/org/bstats/bukkit/Metrics.java, src/main/resources/lang/zh_CN.yml, src/main/resources/plugin.yml
Includes the fixes from 1.18.1-33.1 which were as follows:
* [CORE] https://github.com/Wolfieheart/ArmorStandEditor-Issues/issues/27: Potential fix for PlayerInteractAtEntityEvent Double Firing
* [CI] Update actions/setup-java action to v3
New Version includes the following:
* [CORE] Update to Metrics - Move from Local to org.bstats
* [LANG] Update Simplified Chinese Translation (https://github.com/Wolfieheart/ArmorStandEditor/pull/33)
* [CI] Update actions/checkout action to v3 (https://github.com/Wolfieheart/ArmorStandEditor/pull/34)
* [CI] Update actions/upload-artifact action to v3 (https://github.com/Wolfieheart/ArmorStandEditor/pull/36)
=> [CORE] ArmorStandEditor v1.18.2-34

README.md, pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/resources/config.yml, src/main/resources/plugin.yml
Hotfix Patch: Broken Invisiblity Config Option and Debug supposidely being enabled out of box by default.
This update fixes all of the above issues!
=> ArmorStandEditor 1.18.2-34.2

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/Menu.java, src/main/resources/lang/pt_BR.yml, src/main/resources/plugin.yml
New Permission Nodes asedit.placement and asedit.gravity
add pt_BR translation
----
----
----
----
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the ArmorStandEditor Project Owners have the copyright to use and modify my contribution under the …
=> [CORE] New Permission Nodes asedit.placement and asedit.gravity and add pt_BR translation

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java
More Info to Come Soon.
----
----
----
----
____ …
=> [CORE] ArmorStandEditor 1.19.2-38: Finalize Release

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/CommandEx.java, src/main/resources/config.yml, src/main/resources/plugin.yml
Implement 1.19.3 Support + Other Bugfixes
----
----
----
----
____ …
=> [CORE] ArmorStandEditor 1.19.3

src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/resources/config.yml
=> [CORE] Add in check-interval for Update Checker

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/protections/LandsProtection.java, src/main/resources/config.yml, src/main/resources/plugin.yml
Fix for the Console Spam that lands has been causing #203 
----
----
----
----
____ …
=> [CORE] Hotfix for LandsProtection Error in Console.

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/resources/config.yml, src/main/resources/plugin.yml
=> [CORE] ArmorStandEditor 1.9.4-40.2

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/CommandEx.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditor.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java, src/main/resources/config.yml, src/main/resources/lang/de_DE.yml, src/main/resources/lang/en_US.yml, src/main/resources/lang/es_ES.yml, src/main/resources/lang/fr_FR.yml, src/main/resources/lang/ja_JP.yml, src/main/resources/lang/nl_NL.yml, src/main/resources/lang/pl_PL.yml, src/main/resources/lang/pt_BR.yml, src/main/resources/lang/ro_RO.yml, src/main/resources/lang/ru_RU.yml, src/main/resources/lang/test_NA.yml, src/main/resources/lang/uk_UA.yml, src/main/resources/lang/zh_CN.yml, src/main/resources/plugin.yml
ArmorStandEditor 1.19.4-42.1: Hotfixes and Longstanding Fixes
----
----
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the ArmorStandEditor Project Owners have the copyright to use and modify my contribution under the ArmorStandEditor [License](https://github.com/Wolfieheart/ArmorStandEditor/blob/master/LICENSE.md) for perpetuity.
=> [CORE] ArmorStandEditor 1.19.4-42.1: Hotfixes and Longstanding Fixes

README.md, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditor.java, src/main/resources/config.yml, src/main/resources/plugin.yml
=> [CORE] ArmorStandEditor 1.20.1-43.2

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/CommandEx.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java, src/main/java/io/github/rypofalem/armorstandeditor/Scheduler.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/Menu.java, src/main/java/io/github/rypofalem/armorstandeditor/protections/PlotSquaredProtection.java, src/main/resources/config.yml, src/main/resources/plugin.yml
=> [CORE] ArmorStandEditor 1.20.2-44.1 - QoL Hotfixes

.gitignore, pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/Menu.java, src/main/resources/config.yml, src/main/resources/plugin.yml
=> [CORE] ArmorStandEditor 1.20.6-46.1: Fixing Confusing Mistakes update

src/main/resources/lang/zh_CN.yml
=> Updated zh_CN.yml

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/EquipmentMenu.java, src/main/resources/config.yml, src/main/resources/plugin.yml
Hotfix Update. 
----
- Fix for users being unable to open the Equipment Menu using 1.20.6-46.1
----
----
----
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the ArmorStandEditor Project Owners have the copyright to use and modify my contribution under the …
=> [CORE] ArmorStandEditor 1.20.6-46.2

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/PresetArmorPosesMenu.java, src/main/resources/config.yml, src/main/resources/lang/de_DE.yml, src/main/resources/lang/en_US.yml, src/main/resources/lang/es_ES.yml, src/main/resources/lang/fr_FR.yml, src/main/resources/lang/ja_JP.yml, src/main/resources/lang/nl_NL.yml, src/main/resources/lang/pl_PL.yml, src/main/resources/lang/pt_BR.yml, src/main/resources/lang/ro_RO.yml, src/main/resources/lang/ru_RU.yml, src/main/resources/lang/uk_UA.yml, src/main/resources/lang/zh_CN.yml, src/main/resources/plugin.yml
----
- Support for 1.21.1
- Fix for 
----
----
----
____ …
=> [CORE] ArmorStandEditor 1.21.1-47.1

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/CommandEx.java, src/main/java/io/github/rypofalem/armorstandeditor/Debug.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditor.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/EquipmentMenu.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/Menu.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/PresetArmorPosesMenu.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/SizeMenu.java, src/main/java/io/github/rypofalem/armorstandeditor/modes/ArmorStandData.java, src/main/java/io/github/rypofalem/armorstandeditor/protections/BentoBoxProtection.java, src/main/resources/config.yml, src/main/resources/lang/en_US.yml, src/main/resources/plugin.yml
----
- #597 with Configurable Min/Max (1.21.4 Compatable - Default behaviour)
- Fix for an undisclosed Dupe
- Add team for In Use ArmorStands
- Better Debug Logging
- Fix for running `/ase` commands in Console
- Fix for Present Preset not working
----
----
----
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my …
=> [CORE] ArmorStandEditor 1.24-48

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/CommandEx.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditor.java, src/main/java/io/github/rypofalem/armorstandeditor/modes/ArmorStandData.java, src/main/java/io/github/rypofalem/armorstandeditor/protections/TownyProtection.java, src/main/resources/config.yml, src/main/resources/lang/en_US.yml, src/main/resources/plugin.yml
=> [CORE] ArmorStandEditor 1.21.4-48.1: Fixes

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/CommandEx.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditor.java, src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java, src/main/java/io/github/rypofalem/armorstandeditor/language/Language.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/PresetArmorPosesMenu.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/SizeMenu.java, src/main/resources/config.yml, src/main/resources/lang/de_DE.yml, src/main/resources/lang/en_US.yml, src/main/resources/lang/es_ES.yml, src/main/resources/lang/fr_FR.yml, src/main/resources/lang/ja_JP.yml, src/main/resources/lang/nl_NL.yml, src/main/resources/lang/pl_PL.yml, src/main/resources/lang/pt_BR.yml, src/main/resources/lang/ro_RO.yml, src/main/resources/lang/ru_RU.yml, src/main/resources/lang/uk_UA.yml, src/main/resources/lang/zh_CN.yml, src/main/resources/plugin.yml
1.21.5 Support
Some Fixes... See below
----
----
----
----
____ …
=> ArmorStandEditor 1.21.5-48.2

pom.xml, src/main/java/io/github/rypofalem/armorstandeditor/ArmorStandEditorPlugin.java, src/main/java/io/github/rypofalem/armorstandeditor/CommandEx.java, src/main/java/io/github/rypofalem/armorstandeditor/menu/SizeMenu.java, src/main/resources/plugin.yml
=> [CORE] ArmorStandEditor 1.21.5-48.3: Size Menu does not Compute
